# Generated by Django 6.1.1 on 2026-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text="Identifiant de l'animal ou du lot", max_length=50)),
                ('espece', models.CharField(choices=[('BOVIN', 'Bovin'), ('OVIN', 'Ovin'), ('CAPRIN', 'Caprin'), ('VOLAILLE', 'Volaille'), ('AUTRE', 'Autre')], default='BOVIN', max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nombre', models.PositiveIntegerField(default=1, help_text="Nombre d'animaux dans le lot (si applicable)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal / Lot',
                'verbose_name_plural': 'Animaux / Lots',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('VACCIN', 'Vaccination'), ('TRAITEMENT', 'Traitement'), ('VISITE', 'Visite vétérinaire')], max_length=20)),
                ('date', models.DateField()),
                ('prochaine_echeance', models.DateField(blank=True, help_text='Date du prochain rappel (RF-12)', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Suivi sanitaire',
                'verbose_name_plural': 'Suivis sanitaires',
                'ordering': ['-date'],
            },
        ),
    ]
