# Generated by Django 6.1.1 on 2026-09-18 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'animaux dans le lot (si applicable)", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
