# Generated by Django 6.1.1 on 2026-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(help_text='Type de culture (ex: mil, arachide, maïs)', max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=8)),
                ('date_semis', models.DateField()),
                ('statut', models.CharField(choices=[('SEMIS', 'Semis'), ('CROISSANCE', 'Croissance'), ('RECOLTE', 'Récolte')], default='SEMIS', max_length=20)),
                ('date_recolte_prevue', models.DateField(blank=True, null=True)),
                ('rendement', models.DecimalField(blank=True, decimal_places=2, help_text='Rendement en kg, renseigné après récolte', max_digits=8, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
