# Generated by Django 6.1.1 on 2026-09-18 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='rendement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendement en kg, renseigné après récolte', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='superficie',
            field=models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
