# Generated by Django 6.1.1 on 2026-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en FCFA', max_digits=10)),
                ('categorie', models.CharField(choices=[('CEREALES', 'Céréales'), ('LEGUMES', 'Légumes'), ('FRUITS', 'Fruits'), ('BETAIL', 'Bétail'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('zone', models.CharField(blank=True, help_text='Zone géographique du vendeur', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDU', 'Vendu'), ('SUSPENDU', 'Suspendu')], default='DISPONIBLE', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
