# Generated by Django 6.1.1 on 2026-09-18 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix en FCFA', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
