# Generated by Django 6.1.1 on 2026-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_risque', models.CharField(choices=[('SECHERESSE', 'Sécheresse'), ('FORTES_PLUIES', 'Fortes pluies'), ('VENTS_VIOLENTS', 'Vents violents'), ('VAGUE_CHALEUR', 'Vague de chaleur'), ('AUTRE', 'Autre')], max_length=30)),
                ('zone', models.CharField(help_text='Région ou zone géographique concernée', max_length=100)),
                ('niveau_risque', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], default='MOYEN', max_length=10)),
                ('conseil', models.TextField(blank=True, help_text='Recommandation associée (ex: irrigation)')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date'],
            },
        ),
    ]
