# Generated by Django 6.1.1 on 2026-09-18 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meteo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='destinataires',
            field=models.ManyToManyField(blank=True, related_name='alertes_recues', to=settings.AUTH_USER_MODEL),
        ),
    ]
